### ISSUE TITLE
Load Layer: States and Territories Polygons 2011

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-service#1]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=58
_date:_ Thu Aug  8 05:31:55 2013
_author:_ moyesyside

---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=801](https://code.google.com/p/alageospatialportal/issues/detail?id=801)

Reported by d...@dougashton.com, Nov 29, 2011 
load "layers->political->Australia States and Territories"  and then look at border area. I looked at the border between Canberra and Queanbeyan and also Cameron Corner [http://en.wikipedia.org/wiki/Cameron_Corner](http://en.wikipedia.org/wiki/Cameron_Corner).  The Google supplied borders matched the base layers but "layers->political->Australia States and Territories" matched neither. 
The end result is confusing if you are trying to work out visually which state a point close to the border is in. Important for understanding the operation of Sensitive data rules.

In addition the "layers->political->Australia States and Territories" shows a dog leg in the border near Cameron Corner that I have not been able to see on other maps.
Unfortunately the "View metadata for Australian States .." page [http://spatial.ala.org.au/alaspatial/layers/22](http://spatial.ala.org.au/alaspatial/layers/22)  has broken links.

The same issues apply to the LGA Boundaries layer as well
 Nov 29, 2011 `#1` d...@dougashton.com 
I have just tested "layers->Marine->boundaries->States including coastal waters" and the State boundaries it includes match very closely with the google boundaries and base layers.
This layer also has excellent metadata associated with it and appears authoritative.  
 Nov 29, 2011 `#2` ajay.ranipeta 
setting to Lee for triage 
 Owner: leebel...@gmail.com Nov 29, 2011 Project Member `#3` leebel...@gmail.com 
It boils down to a need for a better States and Territories layer and fixing the broken links in the layer table. Meanwhile, the states/territories with coastal waters will need to suffice.

There is a 2011 states/territories shapefile at [http://abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.001July%202011?OpenDocument](http://abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1270.0.55.001July%202011?OpenDocument). Metadata? Who knows.
 Status: Accepted Owner: yuanfang...@gmail.com Cc: leebel...@gmail.com Nov 29, 2011 Project Member `#4` leebel...@gmail.com 
(No comment was entered for this change.)
 Cc: d...@dougashton.com Feb 15, 2012 `#5` ajay.ranipeta 
Should this be done by Chris as he is set to update the LGA boundaries?  [Issue 670](https://code.google.com/p/ala/issues/detail?id=670)  
 Feb 15, 2012 Project Member `#6` leebel...@gmail.com 
Yes. Over to Chris to lead. Added the updated states/territories to the ListOfOutstandingLayersToBeIngested spreadsheet on Google Docs.
 Owner: chris.fl...@gmail.com Labels: -Priority-Medium Priority-High Apr 24, 2012 Project Member `#7` chris.fl...@gmail.com 
Changing title to reflect that this layer needs to be loaded.
 Summary: LOAD LAYER: States and Territories Polygons 2011 Apr 25, 2012 Project Member `#8` leebel...@gmail.com 
(No comment was entered for this change.)
 Labels: -Priority-High Priority-Low Jul 10, 2013 Project Member `#9` leebel...@gmail.com 
This is a basic layer used in many applications and there appears to be an offset of up to 1km on the ACT boundary so it would be a good idea to update this layer asap. Agree with Doug that the layer "States and territories including coastal waters" is far more accurate
 Cc: -d...@dougashton.com moyesyside Labels: -Priority-Low Priority-High

**Comment by adam-collins** [comment]
Is this OK for prod?

**Comment by Tasilee** [comment]
Yes

**Comment by Tasilee** [comment]
...and remove cl22 (not deprecate)

**Comment by adam-collins** [comment]
On prod. Need to update biocache to point at cl2013 instead of cl22 before removing.

**Comment by Tasilee** [comment]
Looks good. Agree - swap biocache to cl2013 then remove cl22 (asap) to remove problems (e.g., points in ocean etc) and confusion.

**Comment by ansell** [comment]
Those layers may need to be be deprecated in favour of the latest PSMA boundaries, see issue #81

**Comment by Tasilee** [comment]
Agreed.
