### ISSUE TITLE
Upgrade Postgres and PostGIS for ST_MakeValid

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/layers-service#10]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=259
*date:* Mon Sep  9 17:19:08 2013
*author:* natasha....@csiro.au
 ---

To allow for the repair of invalid geometries we need to upgrade to at least postgis version 2.0.0.  

We need to repair geometries to allow SOLR to query based on WKT.

**Comment by adam-collins** [comment]
Will use java instead of postgis for polygons and st_makevalid. Might be worth putting this into biocache-service to attempt fixing invalid geometry.
