### ISSUE TITLE
Load layer : Natural Resource Management Regions 2017

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/layers-service#100]
Latest NRM (2017) available at:

https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7BAB80DA43-CB00-455D-8A3C-70162EB8D964%7D

- [x] Loaded into `nectar-spatial-staging` https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10930
- [x] Pushed to `aws-spatial-prod` https://spatial.ala.org.au/ws/manageLayers/layer/10930
- [x] Waiting on `Complete Resample`/`Complete Reprocess`/`Complete Reindex`
- [x] Swtich regions `menu-config.json` files to point to `cl10930`
- [x] Verify that `cl10930` is working using `regions-test.ala.org.au` and `mdba-regions-test.ala.org.au`
- [x] Switch `regions.ala.org.au` to use this new version
- [x] Respond to helpdesk ticket

**Comment by Tasilee** [comment]
Retain prior versions

**Comment by ansell** [comment]
This issue was opened based on a user query about regions.ala.org.au "Management Regions" being out of date. Investigating I found three NRM layer versions, 2010, 2014 and 2015, and then found a newer version on data.gov.au. All 4 will be kept around.

**Comment by ansell** [comment]
Refs ticket 15320

**Comment by javier-molina** [comment]
URL of related Freshdesk ticket https://support.ehelp.edu.au/a/tickets/15320
