### ISSUE TITLE
Load Layer: Australian Marine Parks

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/layers-service#101]
Parks Australia are currently developing a Marine Park Database web application and would like to access ALA APIs to get a list of species found in each marine park.  In order to do this, PA have requested that we upload the latest Marine Park spatial layer (this hasn't been released yet - due for release by ERIN in July).

In addition, as the layer will be publicly visible without context, they have asked that we modify the polygon labels within the layer as follows:

"The ResName attribute is the one you’ll want to use for labels however it lacks the phrase “Marine Park” on the end of each. So for example Cod Grounds should read Cod Grounds Marine Park. Can you add that? And just to confuse things, that applies to all except Heard Island and McDonald Islands which should end with “Marine Reserve” instead of “Marine Park”. Let me know if that’s not clear or you have any issues with the shapefile."

I'll upload the shape files to nectar-spatial-staging.ala.org.au, when I get access.

**Comment by m-hope** [comment]
Have uploaded the AMP_Outer_ALA.zip file to /data/spatial-data/uploads/australian_marine_parks on the staging server.

**Comment by ansell** [comment]
An example of the metadata that will be attached to the layer is available at:

https://nectar-spatial-staging.ala.org.au/ws/layers/view/more/capad_2014_marine

The most important elements are a short name such as "CAPAD 2014 Marine" that will be shown in the ALA interfaces, a description, the license, a source URL if possible, and a URL for more information from the organisation who published the layer.

**Comment by m-hope** [comment]
Thanks, I’ll chase it down.

**Comment by m-hope** [comment]
Hi @ansell , 

Metadata as follows:

**Description:** 
Consistent with the Australian Government's commitment to   develop a National Representative System of Marine Protected Areas, networks   of Marine Parks have been proclaimed for Commonwealth waters across the   North, North-west, South-west, Temperate East and Coral Sea Marine Regions.   These networks build on previous Marine Protected Area proclamations,   including the South-east Network declared in 2007. This data includes all   marine parks managed by DOEE with the addition of the Heard Island and   McDonald Islands Marine Reserve, which is managed by the Australian Antarctic   Division http://www.heardisland.aq/protection-and-management/marine-reserve   This dataset is released under Creative Commons by Attribution 3.0 Australia   (CC BY 3.0). IMPORTANT INFORMATION FOR MARINE USERS Transitional arrangements   apply to the North, North-west, South-west and Temperate East Marine Parks   Networks and the Coral Sea Marine Park, until management plans come into   effecton the 1st July 2018. These arrangements involve NO CHANGES ON THE   WATER for marine users. Note, there are no changes to management arrangements   in the marine parks that existed prior to the establishment of the new marine   parks, that is, the same restrictions on activities will continue to apply   even where those reserves have been incorporated into new marine parks. More   information is available at www.environment.gov.au/marinereserves. This data   contains spatial and contextual information about Australian Marine Parks   under the jurisdiction of the Commonwealth governments Environment Protection   and Biodiversity Conservation Act 1999, which are managed by the Australian   Government Department of the Environment and Energy. It does not include data   on MPA's in other Australian jurisdictions (e.g. the Great Barrier Reef   Marine Park, State/Territory parks), or Terrestrial Protected Areas with   marine components (eg Pulu Keeling National Park).

**Short Name**
Australia's network of Marine Parks

**Metadata Contact** 
Australian Government Department of the Environment and Energy (marine.metadata@environment.gov.au)

**Organisation Role**
custodian

**Metadata/Reference date**
2018-02-14

**Licence info** 
This data has been licensed under the Creative Commons Attribution 3.0 Australia Licence (CC-BY)

**Licence notes**
©   Commonwealth of Australia (Department of the Environment and Energy) 2018

**Type**
Contextual (polygon)

**Classification**
Area Management => Biodiversity

**Data language**
eng

**Keywords**
reserve, park, conservation, marine

I've taken most of this from the XML metadata file in the layer.ZIP, and chased down a few other things.  As this layer has not officially been published yet there isn't a direct link to the source, but we should have this in July when it is released (I assume we can update this info then?)

**Comment by m-hope** [comment]
Note: once this new Marine Parks layer is loaded... previous layers referring to Marine Parks (eg: https://regions.ala.org.au/Other%20regions/Areas%20for%20Further%20Assessment%20within%20the%20East%20Marine%20Region) should be removed/depreciated.

**Comment by Tasilee** [comment]
Precious layers shouldn't be deprecate in this case @m-hope. Reason: It is good to have a documented history of reserve changes. We need to make sure that the layers are dated as like CAPAD 2014 etc.

**Comment by m-hope** [comment]
No problem @Tasilee , just passing on a request from the owners of the layers... So long as it is clear which is the newer and older layers, I don't think there'll be a problem.

**Comment by ansell** [comment]
This has been loaded onto nectar-spatial-staging, but there is a delay with the cross tabulation tasks that is preventing it being completely pushed through.

The layer is currently at:

https://nectar-spatial-staging.ala.org.au/ws/manageLayers/field/cl10912

**Comment by ansell** [comment]
The cross-tabulation tasks were abandoned until they are fixed. The field was copied to `aws-spatial-prod` and a resample was performed. This resulted in the field being available in cassandra, but not yet in solr. Working through the issues with getting new fields in solr.

**Comment by ansell** [comment]
The field, `cl10912` is now available in biocache, with 400,544 records inside of the marine boundaries:

`https://biocache.ala.org.au/occurrences/search?q=cl10912%3A*`

**Comment by Tasilee** [comment]
This is a similar issue to IPAs in that CAPAD 2018 (and previous) also include all the marine parks. So this issue isn't an issue. We do however need to keep the CAPAD layers (terrestrial and marine) up to date - #114
