### ISSUE TITLE
Load Layer: BioOracle

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#102]
We are weak on the marine layers, and given widespread use of http://www.bio-oracle.org/downloads-to-email.php (inlcuding BCCVL), I'd suggest that we load all Present Surface layers/ to have some alignment. E.g., visualization of these layers with species intersects/stats etc in Spatial Portal before analysis in BCCVL.

**Comment by ansell** [comment]
Would we only load the "Mean" for each of the 18 Present Surface layers? Ie, 18 new layers with one field each?

**Comment by Tasilee** [comment]
I see there is now a V2. Yes, mean certainly and if possible, range for relevant ones :)

**Comment by Tasilee** [comment]
We will luse MERRACLIM layers only due to rationalization.
