### ISSUE TITLE
Create an issue template with the contextual layer loading steps in it as tasks

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/layers-service#117]
It would be useful to create an issue template with the contextual layer loading steps in it as tasks to streamline the layer loading process.

The current documentation for layer loading is at:

https://wiki.ala.org.au/wiki/Spatial-layer-loading

**Comment by Tasilee** [comment]
@ansell: This came up a few weeks ago with @peggynewman during my review of spatial layers. I totally agree.

**Comment by ansell** [comment]
@Tasilee The initial load layer template, including the investigation and approval steps above are in a template at:

https://github.com/AtlasOfLivingAustralia/layers-service/blob/master/.github/ISSUE_TEMPLATE/load-layer.md

Feel free to edit that to add new steps or tweak the existing steps as necessary

Initial attempt at using the template will be for `CAPAD 2018 Marine` in #114

**Comment by Tasilee** [comment]
Thanks @ansell - I've done a few small edits to the md file - it looks good to me. I'd strongly suggest the test should be be on #113 as this is required anyway for analyses. It ticks 1,34,5,6,7,8,9,10,11,13,14,15.

**Comment by ansell** [comment]
@Tasilee my bad, yes, #113 (which is already uploaded on nectar-spatial-staging but is missing metadata) should be first:

https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10948

**Comment by ansell** [comment]
The template seems to work okay so far. Closing this issue based on that.

**Comment by Tasilee** [comment]
Thanks @ansell
