### ISSUE TITLE
Fix missing objects: 5 objects in layer nrm2017_qld2019 (cl10947) are present in geoserver but not in the spatial portal api

### ISSUE THREAD

**Issue by cofiem** [AtlasOfLivingAustralia/layers-service#118]
Hello,

I maintain an instance of biocollect and ecodata which uses the ALA's spatial server.

I'm trying to resolve an issue with missing objects in the layer `nrm2017_qld2019` (cl10947). The objects all show up on the ALA's spatial portal, but in biocollect there are some objects missing on the 'globe' dropdown in the maps when creating or editing a project or site.

I've looked into this, and the issue seems to be that the geoserver contains the 61 expected objects, but the spatial server api is missing 5 objects. Biocollect uses the spatial service api, so the items are missing in biocollect.

I've compared these endpoints:

- https://spatial.ala.org.au/layers-service/objects/cl10947
- https://spatial.ala.org.au/ws/field/cl10947?start=0&pageSize=500
- https://spatial.ala.org.au/geoserver/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=ALA:nrm2017_qld2019&outputFormat=application/json&propertyName=NRM_REGION

The missing items in the two spatial server API, but present in the geoserver API are:

- Cape York (id 7)
- Norfolk Island (id 27)
- South Australian Arid Lands (id 43)
- South Australian Murray Darling Basin (id 44)
- South NRM Region - Macquarie Islands (id 42)

I've compared this to the older NRM region `nrm_regions_2017` (cl10930). It has 63 items in all the three endpoints, which is what I expect.

Could you please look into this? I think the three APIs should return the same results, which should include the missing 5 items. There should be 61 objects in total.

**Comment by nickdos** [comment]
@adam-collins could you take a look at this please?

**Comment by ansell** [comment]
For reference, biocache is showing the expected 61 objects in facet queries for `cl10947`:

```
https://biocache-ws.ala.org.au/ws/occurrences/facets/download?q=cl10947%3A*&facets=cl10947&count=true&lookup=true
```

**Comment by adam-collins** [comment]
61 objects now in 
- https://spatial.ala.org.au/layers-service/objects/cl10947
- https://spatial.ala.org.au/ws/field/cl10947?start=0&pageSize=500

The problem was that these areas had self intersecting polygons and were excluded by the validity test.

**Comment by cofiem** [comment]
I've tested this out, and it looks to be fixed. Thanks very much!
Is there any chance of the areas being excluded again in the future?

**Comment by adam-collins** [comment]
I am currently reviewing the process for this issue. 

This issue will remain open until the underlying issue is resolved.

**Comment by adam-collins** [comment]
This will not be an issue for future layers.

The CAPAD 2010 Terrestrial was the only other layer with an issue. It is now consistent.
- The aggregation on PA_ID instead of NAME in the web services other than geoserver caused 5 areas to merge into 1. 
- The aggregation on TYPE was case insensitive in the web services other than geoserver causing 2 areas to merge into 1.
