### ISSUE TITLE
Create an issue template with the steps for removing layers

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/layers-service#119]
It would be useful with the upcoming spatial layer removals process to have an issue template with the steps for removing layers.

Doing a single removal and using the steps from it for the template would be useful.

**Comment by Tasilee** [comment]
Good point @ansell. There will be a lot of removals. I won't know most of the steps involved, but one thing that should happen is a newsletter article or blog explaining the rationale and plan.

**Comment by peggynewman** [comment]
I'm talking to comms about the blog article. @adam-collins could you work this list up so we can test it out on one or just a few layers for deletion?

Is the list of steps different for contextual and environmental layers?

Good starting layers for removal would be:

Environmental: https://spatial.ala.org.au/ws/manageLayers/layer/999
Contextual: https://spatial.ala.org.au/ws/manageLayers/layer/606/

**Comment by ansell** [comment]
@adam-collins Issue templates go in this directory: 

https://github.com/AtlasOfLivingAustralia/layers-service/tree/master/.github/ISSUE_TEMPLATE

We can use the load layer template as an example of the syntax.

**Comment by ansell** [comment]
A task list for deletions was added by Adam in this commit:

https://github.com/AtlasOfLivingAustralia/layers-service/commit/c263100a925d4b784690277c543b3f5fb389c1de

@peggynewman @Tasilee Which layer would be best for using as a test case of those steps?

**Comment by Tasilee** [comment]
Thanks Peter and Adam. I'd suggest "Sodicity" as it isn't working anyway.
