### ISSUE TITLE
BUG - Geonetwork metadata links all broken

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#120]
The links in metadata to 'More information', for example 

More information | https://spatial.ala.org.au/geonetwork/srv/en/metadata.show?uuid=1e489099-1543-43d3-a9f3-345ec5646c03 | 

are all broken, due I presume to geoNetwork being down?

**Comment by ansell** [comment]
My vague recollection is that geonetwork was not setup or is partially setup on the new server, but we had a discussion at some point in the past and it was agreed that it wasn't a priority at that point in time. (Of course priorities change over time)

**Comment by Tasilee** [comment]
You are probably right @ansell . But we should be exposing layer metadata on geonetwork as I can't see that the original argument for doing so has changed. @adam-collins ?
