### ISSUE TITLE
Load Layer: Physiographic regions of Australia

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#13]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=700
*date:* Sun Jun 15 18:55:37 2014
*author:* leebel...@gmail.com
 ---

Physiographic regions of Australia is a high-level base layer useful for defining environmental characteristics, particularly to the freshwater environment.

If possible, I would like to have this layer for demos at the Australian Society for Fish Biology and Australian Society for Limnology Congress Darwin 30th June.

Metadata and data sent to Adam

**Comment by adam-collins** [comment]
Concatenated name + regolith type for physioreg (2021) and physioprov (2022). Is this OK?

**Comment by Tasilee** [comment]
Excellent for hover tool! But, we need a base legend with name (only) in both cases (provinces and regions).

**Comment by adam-collins** [comment]
Added legends. May need to refresh cache.

**Comment by Tasilee** [comment]
Gorgeous!

**Comment by adam-collins** [comment]
On prod.
