### ISSUE TITLE
Load layer: Geological regions of Australia

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#14]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=701
_date:_ Sun Jun 15 19:21:34 2014
_author:_ leebel...@gmail.com

---

Geological Regions of Australia is a basic layer that has been missing from our list and will be useful when combined with surface geology, physiographic regions, catchments and other geophysical layers we have.

Attached file contains the GIS data and the metadata can be found at [http://www.ga.gov.au/metadata-gateway/metadata/record/gcat_32366](http://www.ga.gov.au/metadata-gateway/metadata/record/gcat_32366)

**Comment by adam-collins** [comment]
name: georegions
id: 2020

Is this OK for prod?

**Comment by Tasilee** [comment]
Checked metadata and display so yes - toProd

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Coloured classes? :)
