### ISSUE TITLE
Load layer: Ecohydrological classification (Janet Stein)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#15]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=709
_date:_ Tue Jun 17 23:00:31 2014
_author:_ leebel...@gmail.com

---

This layer would be extremely useful for the 'freshwater conference' demo (July 1).

From Janet Stein:

The adopted 30 group ecohydrological environment classification can be downloaded from [https://alliance.anu.edu.au/access/content/group/a1af2671-aa0f-4b77-00b6-138573bf3e83/hydroecological%20regionalisation/](https://alliance.anu.edu.au/access/content/group/a1af2671-aa0f-4b77-00b6-138573bf3e83/hydroecological%20regionalisation/) - demstreamsv293.zip has a vector representation (shape format) of the stream network with classification group attributed or if you prefer raster formats there is a zipped arc/info workspace (allstdg30cat.zip) containing two rasters of the ecohydrological classification for, respectively,  the raster stream network and its sub-catchments.

Later (probably via BOM geofabric data, but left here for context)-

(However, the underpinning spatial layers and associated  environmental attributes were all updated for the Geofabric and other more recent projects so this data is not current. The other classifications can probably be supplied in the form of a lookup table to link to the stream layer if you would like  them as well.)

**Comment by ansell** [comment]
I don't have login access to ANU to download this. What type of licensing is available on the shapefile?

There is an excel file downloadable from the following URL that appears to have some of the information but would need to be transformed from point (lat/long) measurements to something more useful before uploading:

http://atlas.track.org.au/maps/flow-regime

**Comment by Tasilee** [comment]
Emailing Janet Stein

**Comment by Tasilee** [comment]
Janet Stein retires so no support: kill. Some geofabric layers #32 suffice
