### ISSUE TITLE
Load layer: Agroclimatic classification of Australia

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#19]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=761
_date:_ Wed Jul 30 18:30:14 2014
_author:_ leebel...@gmail.com

---

In searching for a layer defining Australian terrestrial biomes, I was recommended Hutchinson et al's Agroclimatic classification. The shapefile has been supplied by Jannet Stein (co-author on the 2005 paper).

I'll need to create a metadata entry for this so if a preliminary entry could be made in the Layers Table, I'll fill in the remaining details.

**Comment by adam-collins** [comment]
The shapefile has agrocodes, “H”, “D5”, “B2”, “E6”, “F3”, “E2”, “J2”, “I3”, ”E1”, “I1”, ”E7”, “I2”, “E3”, “G”, ”F4”, ”E4”, “B1”, ”J1"

Need a lookup to code descriptions.

name: agroclimate
id: 2052

**Comment by Tasilee** [comment]
Yep, sure do. Suggest https://www.dropbox.com/s/68csmni223rrvvy/Hutchinson_Global%20Agroclimatic%20Classification_2005.pdf?dl=0 

Table 2:

B1 Very cold winters with summers too short for crop growth
B2 Less severe winters and longer moist summers suitable for some crops
D5 Moisture availability high in winter-spring, moderate in summer, most plant growth in spring
E1 Classic “Mediterranean” climate with peaks of growth in winter and spring and moderate growth in winter
E2 “Mediterranean” climate, but with drier cooler winters and less growth than E1
E3 Most plant growth in summer, although summers are moisture limiting. Temperature limits growth in winter
E4 Growth is limited by moisture rather than temperature and the winters are mild. Growth is relatively even through the year
E6 Semi-arid climate that is too dry to support field crops. Soil moisture tends to be greatest in winter
E7 Moisture is the main limit on crop growth. Growth index lowest in spring
F3 Cooler end of the warm, wet sub-tropical climates 
F4 Warmer and wetter than F3 
G Desert, supporting very little plant growth due to water limitation
H Semi-arid, with some growth in the warm season, but too dry for cropping
I1 Strongly developed wet and dry seasons with plant growth determined by moisture availability
I2 Temperature and moisture are more seasonal than for I1 and the growing season is shorter
I3 This has cooler winters than I1 and I2 with a growing season lasting at least six months
J1 Moisture and temperature regime supports growth for 8–9 months of the year, with a 3–4 month dry season
J2 As for J1 but with a shorter dry season Limited areas on the east coast of Cape York Peninsula

Metadata (layers table) updated.

**Comment by adam-collins** [comment]
Updated with non-self referencing values.

**Comment by Tasilee** [comment]
? Coloured polygons and legend?

**Comment by adam-collins** [comment]
colours!

**Comment by Tasilee** [comment]
:)

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Unreadable legend
![capture](https://cloud.githubusercontent.com/assets/6656350/6742817/18ae7374-cee7-11e4-9977-92ce24339e26.jpg)
