### ISSUE TITLE
Load Layer: dis_coast_me

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-service#2]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=59
*date:* Thu Aug  8 05:32:19 2013
*author:* moyesyside
 ---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=829](https://code.google.com/p/alageospatialportal/issues/detail?id=829)

Project Member Reported by chris.fl...@gmail.com, Jan 5, 2012 
GA_distance_to_coast
 Jan 5, 2012 Project Member `#1` chris.fl...@gmail.com 
provider: GA_distance_to_coast
 Apr 24, 2012 Project Member `#2` chris.fl...@gmail.com 
Delete layer dist_coast - this is in decimal degrees and not useful. Use dist_coast_me in its place.
 Apr 25, 2012 Project Member `#3` leebel...@gmail.com 
(No comment was entered for this change.)
 Labels: -Priority-Medium Priority-Critical Apr 25, 2012 Project Member `#4` chris.fl...@gmail.com 
There is a problem with the source data for this layer - no prj file is supplied, and the listed datum on the website (GDA94) results in a warped geotiff. Will need to contact GA about this.
 Labels: -Priority-Critical Priority-Low Jul 10, 2013 Project Member `#5` leebel...@gmail.com 
This needs a fix or two, namely (as above and more)

1. Remove layer ID=819	(substrate_distcoast) as it is useless as is and superceeded by ID=946

2. Layer ID=946 (dist_coast) is actually distance (km)/100 so we either need to change the legend or x 100 (latter better)

3. Classification of ID=946 is incorrect as "Marine | Distance". It should be Classification 1 = "Distance" 

 Cc: leebel...@gmail.com moyesyside Labels: -Priority-Low Priority-High

**Comment by adam-collins** [comment]
Is this OK for prod?

**Comment by Tasilee** [comment]
Yes. I've update the metadata (dev). Delete (not deprecate) el946. el819 (from Kristen) seems bung so unsure how it compares with el2016

**Comment by adam-collins** [comment]
On prod.

**Comment by adam-collins** [comment]
Disabled el946
