### ISSUE TITLE
Load Layer: Bio-Oracle global marine layers

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#20]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=763
*date:* Thu Jul 31 15:46:25 2014
*author:* leebel...@gmail.com
 ---

This is a recent compilation of global environmental marine layers that have been designed to use in species distribution modeling.

Data: [http://www.oracle.ugent.be/DATA/70_70_RV/BioOracle_7070RV.rar](http://www.oracle.ugent.be/DATA/70_70_RV/BioOracle_7070RV.rar)

Higher priority than all loads except capad marine 2014 (for Dan G for fishmap only), 701 and 750

**Comment by adam-collins** [comment]
Need metadata. Do the scales (blue-red) need reversing? Layer units?
2053	calcite
2054	chlomax
2055	chlomean
2056	chlomin
2057	chlorange
2058	cloudmax
2059	sstmin
2060	sstrange
2061	silicate
2062	sstmax
2063	sstmean
2064	ph
2065	phos
2066	salinity
2067	nitrate
2068	parmax
2069	parmean
2070	damean
2071	damin
2072	dissox
2073	cloudmean
2074	cloudmin
2075	damax

**Comment by Tasilee** [comment]
Sorry. These data are now superseded by #22
