### ISSUE TITLE
Load Layer: Percentage of clear observations on which water was detected - filtered for confidence

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#21]
High priority to address lack of freshwater environmental data

The WOfS web services are available at: http://eos.ga.gov.au/geoserver. This is the location of the 5 underlying web services that create the WOfS product. They are for each grid cell:

· the number of clear satellite observations over the period (1998-2012)
· the number of occasions water was detected
· the percentage of clear observations on which water was detected
· the confidence (or probability) that a water observation in this location is correct. This is a percentage, based on a number of factors including the slope of the land and the existence of other corroborative evidence.
· The percentage of clear observations on which water was detected, filtered for confidence.

NOTE: The last layer in the list – the Filtered layer – is the one we recommend to start with, as it removes a lot of cloud shadow and other artefacts from the water extents.

If you have any issues connecting with the services or getting transparencies to work, please let me know. The filtered layer is the one which will be available to the public through the NFRIP Portal, which can be found at: http://www.ga.gov.au/hazards/flood/floods.html

 Leo Lymburner (Geoscience Australia)

**Comment by Tasilee** [comment]
As you note, the layer currently looks like it has a series of imagery artefacts not present in http://www.ga.gov.au/flood-study-web/#/water-observations
![capture](https://cloud.githubusercontent.com/assets/6656350/11326166/3260b6c8-91b6-11e5-8bd5-f9a9b10e3854.jpg)

but this is one terrific layer for freshwater work!

I used the WMS at http://eos.ga.gov.au/geoserver/NFRIP-WOfS/wms? in the SP (WaterSummaryFiltered)

**Comment by adam-collins** [comment]
ready for metadata

**Comment by Tasilee** [comment]
Done on Dev

**Comment by adam-collins** [comment]
on prod.
