### ISSUE TITLE
Load Layer: Marspec Marine environmental data

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#22]
Marspec is a higher resolution recommended (Piers Dunstan and Dan Gledhill) suite of marine layers and should be loaded as a higher priority to fill the marine layer gap. See http://www.marspec.org/ and link to download data. Note also the need to reference associated tables for actual values during processing. Ideally, Bio1-17 plus Table 1 (30 arc seconds).

**Comment by adam-collins** [comment]
Bio1-17. These are large layers. 

2088,marspec_01,Marspec East/West Aspect
2089,marspec_02,Marspec North/South Aspect
2090,marspec_03,Marspec Plan Curvature 
2091,marspec_04,Marspec Profile Curvature
2092,marspec_05,Marspec Distance to Shore
2093,marspec_06,Marspec Bathymetric Slope
2094,marspec_07,Marspec Concavity
2095,marspec_08,Marspec Mean Annual SSS
2096,marspec_09,Marspec Minimum Monthly SSS
2097,marspec_10,Marspec Maximum Monthly SSS
2098,marspec_11,Marspec Annual Range in SSS
2099,marspec_12,Marspec Annual Variance in SSS
2100,marspec_13,Marspec Mean Annual SST
2101,marspec_14,Marspec SST of the coldest ice-free month
2102,marspec_15,Marspec SST of the warmest ice-free month
2103,marspec_16,Marspec Annual Range in SST
2104,marspec_17,Marspec Annual Variance in SST

**Comment by adam-collins** [comment]
Need metadata.

**Comment by Tasilee** [comment]
All metadata (dev) completed. ToProd

**Comment by Tasilee** [comment]
...and remove (delete) el800, el801, el802, el803, el804, el805 (all CARS layers)

**Comment by adam-collins** [comment]
On prod.

**Comment by adam-collins** [comment]
CARS layers disabled.
