### ISSUE TITLE
Load Layer - CAPAD 2012

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#24]
We need to retain the various bi-annual CAPAD layers at least from 2010 so the 2012 should be added. 

Data/metadata can be found at http://www.environment.gov.au/metadataexplorer/explorer.jsp using "CAPAD"

**Comment by adam-collins** [comment]
Needs metadata.
name: capad_2012
id: 2081

**Comment by Tasilee** [comment]
Metadata done. Waiting on response to broken source link at Environment Australia

**Comment by Tasilee** [comment]
Metadata completed.

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
A classic where we need by default to display top-level classification (as per CAPAD 2010) with option to display individual areas.

**Comment by Tasilee** [comment]
Done, aside from SP#74 which is a generic issue?

**Comment by Tasilee** [comment]
Urgently need to display classification
