### ISSUE TITLE
Load Layer: CAPAD 2012 Marine

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#25]
We need to retain the various bi-annual CAPAD layers at least from 2010 so the 2012 should be added. 

Data/metadata can be found at http://www.environment.gov.au/metadataexplorer/explorer.jsp using "CAPAD"

**Comment by adam-collins** [comment]
Needs metadata.
name: capad_2012_marine
id: 2080

**Comment by Tasilee** [comment]
Metadata done. Waiting on response to broken source link at Environment Australia

**Comment by Tasilee** [comment]
Metadata completed.

**Comment by adam-collins** [comment]
On prod.
