### ISSUE TITLE
Load Layer - Fire Regime Niches

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#27]
Fire plays an extremely important role in Australia's ecosystems. This dataset resulting from an ACEAS Workshop (http://www.aceas.org.au/index.php?option=com_content&view=article&id=75&Itemid=77) provides an effective layer for ecologists, consultants and land managers to use in relation to other ALA data. The data can be downloaded from http://aceas-data.science.uq.edu.au/portal/ under Fire Regime Niches (click point and select download).

**Comment by adam-collins** [comment]
Needs metadata.
name: fire_regime_niches
id: 2076

**Comment by Tasilee** [comment]
metadata updated.

**Comment by Tasilee** [comment]
For this type of contextual (national coverage, classes with multiple polygons), a map with coloured classes (colour fill with no outlines) would be nice. I'll check on a more general issue.

**Comment by adam-collins** [comment]
Ranged colour fill created.

**Comment by Tasilee** [comment]
Much much nicer! Thanks Adam. That class selector is awesome BTW

**Comment by adam-collins** [comment]
On prod.
