### ISSUE TITLE
Load layer: Re-process Surficial geology layer

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-service#3]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=60
_date:_ Thu Aug  8 05:32:43 2013
_author:_ moyesyside

---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=994](https://code.google.com/p/alageospatialportal/issues/detail?id=994)

Project Member Reported by chris.fl...@gmail.com, May 29, 2012 
Need to source a gridded version of this dataset - the only copy I can find of the raw data consists of extremely large shape files.

The layer then needs to be re-loaded using the GridClassBuilder

 Jun 18, 2012 Project Member `#1` leebel...@gmail.com 
Emailed Leo Lymburner to see if he can get a copy in grid format.
 Labels: -Priority-Medium Priority-High Jun 6, 2013 Project Member `#2` chris.fl...@gmail.com 
Hi Lee,

This one has fallen through the cracks - did you ever hear back about it? We had also discussed this with Kristen. Is it still a high priority?

Cheers,
Chris
 Cc: -adam_col...@tpg.com.au moyesyside Jun 6, 2013 Project Member `#3` leebel...@gmail.com 
I've emailed Leo again about this. If no response, I'll ask Kristen as I know she will have this as a soil surrogate, but format - who knows.
 Jul 8, 2013 Project Member `#4` leebel...@gmail.com 
Kristen Williams has these data and could supply a 250m gridded version. Please pursue, via Miles?

NOTE: The reason the gridded data is needed is for processing for Tabulation and I suspect, Add to Map | Areas | Gazetteer polygon.

Remains a high priority as the layer is available to map but not to use in analyses. Inconsistent. Handed to Chris.
 Owner: chris.fl...@gmail.com Cc: -chris.fl...@gmail.com leebel...@gmail.com

**Comment by ansell** [comment]
Two versions of the Surface Geology of Australia, 2012 edition from Geoscience Australia are available at data.gov.au.

1:1 000 000 scale:

https://data.gov.au/dataset/8284767e-b5b1-4d8b-b8e6-b334fa972611

1:2 500 000 scale:

https://data.gov.au/dataset/4a91fff8-ed51-4994-b358-066497e25c8c

**Comment by Tasilee** [comment]
If we can handle it, we would always opt for the better resolution these days. 1: 1 million. That is pretty coarse anyway.
