### ISSUE TITLE
Load layer: CAPAD 2014 Terrestrial

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#30]
The latest version of CAPAD: http://www.environment.gov.au/metadataexplorer/explorer.jsp and enter CAPAD into "Search Title", select 2014 (Terrestrial)

**Comment by adam-collins** [comment]
Needs metadata.
name: capad_2014_terrestrial
id:2079

**Comment by Tasilee** [comment]
Metadata done. Waiting on response to broken source link at Environment Australia

**Comment by Tasilee** [comment]
Metadata completed.

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
As other CAPAD layers - need by default to display top-level classification (coloured) with option for lower level.

**Comment by Tasilee** [comment]
Done, aside from SP#74 which is a generic issue?

**Comment by Tasilee** [comment]
Urgently need to display classification
