### ISSUE TITLE
Load Layer: CAPAD 2014 Marine

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#31]
The latest version of CAPAD: http://www.environment.gov.au/metadataexplorer/explorer.jsp and enter CAPAD into "Search Title", Select 2014 marine

**Comment by adam-collins** [comment]
Needs metadata.
name: capad_2014_marine
id:2078

**Comment by Tasilee** [comment]
Metadata done. Waiting on response to broken source link at Environment Australia

**Comment by Tasilee** [comment]
Metadata completed.

**Comment by adam-collins** [comment]
On prod.
