### ISSUE TITLE
Load Layer: World ecoregions with exceptional biodiversity

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#35]
See http://www.worldwildlife.org/publications/global-200 for data and ref. This layer will be complementary to CAPAD etc and helps to define world biomes for $values of ecosystem services:

WWF’s Global 200 project analyzed global patterns of biodiversity to identify a set of the Earth's terrestrial, freshwater, and marine ecoregions that harbor exceptional biodiversity and are representative of its ecosystems.

We placed each of the Earth's ecoregions within a system of 30 biomes and biogeographic realms to facilitate a representation analysis. Biodiversity features were compared among ecoregions to assess their irreplaceability or distinctiveness. These features included species richness, endemic species, unusual higher taxa, unusual ecological or evolutionary phenomena, and the global rarity of habitats.

This process yielded 238 ecoregions--the Global 200--comprised of 142 terrestrial, 53 freshwater, and 43 marine priority ecoregions.

Effective conservation in these ecoregions would help conserve the most outstanding and representative habitats for biodiversity on this planet.

**Comment by adam-collins** [comment]
Needs metadata.
2085	g200_marine, Marine
2084	g200_terr, Terrestrial
2083	g200_fw, Fresh Water

**Comment by Tasilee** [comment]
Metadata done for all. Legends would be nice but lotsa classes. Error on mapping marine layer.

**Comment by adam-collins** [comment]
Corrected marine error and added colour.

**Comment by Tasilee** [comment]
And very nice it looks!

**Comment by adam-collins** [comment]
On prod.
