### ISSUE TITLE
Load layer: World seagrass richness layer

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#36]
These data are publicly available and will help to fill the gap in marine layers. Data at https://www.dropbox.com/s/k7cf2rahagooenw/WCMC-015-SeagrassRichness2003.zip?dl=0
 
See http://data.unep-wcmc.org/datasets/9 for metadata etc.

**Comment by adam-collins** [comment]
Needs metadata.
name: seagrass
id: 2077

**Comment by Tasilee** [comment]
metadata done. toProd

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Any chance we can colour-scale this layer? It would improve understanding no end.

**Comment by adam-collins** [comment]
Added colours.
