### ISSUE TITLE
Load Layer: Important Bird Areas (IBAs) - Australia

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#37]
The Important Bird (and Biodiversity) Areas (see http://www.birdlife.org.au/projects/important-bird-areas/iba-maps) are internationally recognised and IUCN-supported area of significane for bird species. They are in addition to CAPAD areas.

Criteria for IBAs (metadata): http://www.birdlife.org/datazone/info/ibacritglob

International data: http://www.birdlife.org/datazone/geomap.php?r=i&bbox=-150%20-50%20150%2080 but can't see how to get GIS data.

No counterparts to deprecate.

**Comment by adam-collins** [comment]
Could only find Australian IBAs. Needs metadata.

name: iba_australia
id: 2087

**Comment by Tasilee** [comment]
At this stage, let's just load the Australian IBAs, the shapefile and kml files are at http://www.birdlife.org.au/projects/important-bird-areas/iba-maps. I'll do the metadata now.

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Were there classes in the data to class areas as "seabird island species", "resident waterbirds", "migratory shorebirds", "mallee birds", "threatened woodland birds", "rainforest birds" and "other"?

**Comment by ansell** [comment]
Just to clarify, did you want a single category based field or a field for each category?

The field list for the source behind 2087 currently is:

<img width="338" alt="screen shot 2016-08-23 at 10 22 50 am" src="https://cloud.githubusercontent.com/assets/82365/17876210/b0f16310-691b-11e6-887a-9dc597c67d41.png">

**Comment by ansell** [comment]
The international data is available under a non-commercial and not to be distributed license, so not sure what we could use it, as anything we would use it for would be distribution:

http://www.birdlife.org/datazone/info/spcdownload

**Comment by Tasilee** [comment]
We need to draw the line somewhere rational on what international layers we include. I'd skip this one as there is a case for analysis of Oz data but not external.

**Comment by ansell** [comment]
On your other question about the categories though, there doesn't seem to be any metadata or data dictionary attached to the australian iba shapefile, so not completely sure how to interpret most of the fields, but the unique values for the latter fields are the following if that helps:

```
Field Name	Unique Values
REGENT_HE	0, 1
CARNABY_BC		0, 1
CAR_BAU_BC		0, 1
AUST_BITT	0, 1
FAIRY_TERN	0, 1
SWIFT_PARR	0, 1, 2
WATERBIRDS	0, 1, 2, 3, 4
THREAT_STA	0, 1, 2, 3, 4
IBA_CRITER	1, 2, 3, 4
```

The IBA_CRITER column may refer to A1/A2/A3/A4 from http://www.birdlife.org/datazone/info/ibacritglob

The THREAT_STA column may refer to the Red List categories, but no idea how they would map http://www.birdlife.org/datazone/info/spcredcat

The others except for WATERBIRDS all seem to be species specific so they may benefit from a special species distribution for those.

**Comment by Tasilee** [comment]
Without a lookup, it is hard to say. Suggest you marry an example as in http://www.birdlife.org/datazone/sitefactsheet.php?id=24809 and hopefully the values will be determined?
