### ISSUE TITLE
Load Layer: FAO Fishing Statistical Areas

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#38]
This data appears to be a useful breakdown of areas used for FAO fishing statistics. Data and metadata can be found at http://www.fao.org/geonetwork/srv/en/main.home?uuid=ac02a460-da52-11dc-9d70-0017f293bd28

Type = Contextual
Extent = global
Useful for area definitions - area reports and cross-tabulation

**Comment by linaizhong** [comment]
Hi Lee,

I have loaded the FAO_AREAS into spatial-dev.ala.org.au, the display name is FAO Major Marine Fishing Areas. Could you please provide the metadata for this?

Best regards,
Alan

**Comment by Tasilee** [comment]
Metadata added to dev system

**Comment by M-Nicholls** [comment]
Migrated to production
