### ISSUE TITLE
Load Layer: World Anthropogenic Biomes (2000)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#39]
http://sedac.ciesin.columbia.edu/data/set/anthromes-anthropogenic-biomes-world-v2-2000/data-download

Either geotif or ESRI grid files

**Comment by adam-collins** [comment]
Needs metadata.

name: a2000_global
id: 2086

**Comment by Tasilee** [comment]
metadata completed

**Comment by Tasilee** [comment]
...and an excellent map BTW!

**Comment by linaizhong** [comment]
Hi Adam, It looks like you have already add this to the spatial-dev.ala.org.au. Do we need to put this into spatial.ala.org.au?

Regards,
Alan

**Comment by adam-collins** [comment]
This one is ready to go to prod.

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Needs coloured classes if possible.

**Comment by adam-collins** [comment]
Added coloured classes.
