### ISSUE TITLE
Layer Issue: ERIN Threatened Species layers

### ISSUE THREAD

**Issue by peterdohertyala** [AtlasOfLivingAustralia/layers-service#40]
Layers look great but there are a few issues:
    Colour is the same for likely and maybe layers - different colours would be useful
    Titles are not including likely and maybe text - just a 1 or nothing
    Pressing the "I" button returns - "No metadata"

**Comment by adam-collins** [comment]
For SP, expert distributions in Add to map | Species and Tools | Area report:
- Now using varying colours for created areas. They no longer default to red.
- There are other sources of Expert distributions. Likely and maybe were specific to the SNES lists. 
- To avoid layers with the same name SP may add a number to the end of the layer name (1) or (2).
- SP metadata links for Expert distributions are fixed for the "I" and in the Area report expert distribution list "link". Some expert distributions do not have a external metadata link.
