### ISSUE TITLE
load layer: nrm 2014

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/layers-service#46]
http://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7BAB80DA43-CB00-455D-8A3C-70162EB8D964%7D

layer id: 2111
layer name: nrm2014

Ready for metadata

**Comment by Tasilee** [comment]
Metadata is good. Edited a few fields (dev).
Renamed old NRM regions to NRM Regions 2010 (retain for now)
Extent is national
Coverage is total
Unique polygons
Cross-tab - yes (2010 no)
Facet - yes (2010 - no)

Priority high due to MERIT support

**Comment by adam-collins** [comment]
On prod. Cross-tab is running.
