### ISSUE TITLE
Load Layer Phenology Max 1 2002 and 2010 (2 layers)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#47]
A new suite of Australian phenology layers are available. As a trial, please load 

max 1 t 2002.nc      (dry year)
max 1 t 2010.nc      (wet year)

from http://data.c3.uts.edu.au/thredds/catalog/auscover/MODIS_Phenology_Product_Australia_0.05_deg_V1.1/Pheno_Max/max_t/catalog.html

Data is in netCDF format

Metadata is at http://www.auscover.org.au/geonetwork/srv/en/main.home?uuid=03312acf-5f95-4fcc-9802-52801afe4e85

Mark Brioch will be sending through a few aggregated layers at some point.

**Comment by adam-collins** [comment]
Ready for metadata if they look OK.
phenomax1_2012
phenomax1_2002

**Comment by Tasilee** [comment]
Metadata done

**Comment by adam-collins** [comment]
on prod
