### ISSUE TITLE
Murray-Darling Basin Layers

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#48]
I’ve just learnt that a bunch of our spatial is available for ready download either from our website (at http://www.mdba.gov.au/river-data/spatial-data-services/spatial-information) or from data.gov.au. There are a couple that I think would be useful to have as optional layers in the portal, though I’m still chasing down catchment boundaries – hope to have these to you soon.

Links to the spatial data on data.gov.au are:

Water Quality Zones (DONE)
http://data.gov.au/dataset/water-quality-zones 

Surface Water SDL resource units
http://data.gov.au/dataset/surface-water-sdl-resource-units 

Surface Water SDL resource units
http://data.gov.au/dataset/groundwater-sdl-resource-units 

Murray-Darling Basin Water Resource Plan Areas – surface water
http://data.gov.au/dataset/murray-darling-basin-water-resource-plan-areas-surface-water  

Murray-Darling Basin Water Resource Plan Areas – groundwater
http://data.gov.au/dataset/murray-darling-basin-water-resource-plan-areas-groundwater

**Comment by ansell** [comment]
Surface water SDL resource units loaded into spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10832

**Comment by ansell** [comment]
Ground water SDL resource units loaded into spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10833

**Comment by ansell** [comment]
Surface water Resource Plan Areas loaded into spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10834

**Comment by ansell** [comment]
Ground water Resource Plan Areas loaded into spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10835
