### ISSUE TITLE
Load Layer: New Weathering Intensity Index (WII)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-service#5]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=67
*date:* Thu Aug  8 05:36:30 2013
*author:* moyesyside
 ---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=954](https://code.google.com/p/alageospatialportal/issues/detail?id=954)

Project Member Reported by chris.fl...@gmail.com, Apr 29, 2012 
New version of this layer has been supplied by Kristen. See below. Also, the metadata for this layer needs to be loaded into getnetwork - see attached file.

Hi Lee,

I have created a corrected wii layer which applies a different resampling
method:
[ftp://ftp.csiro.au/wil00p/](ftp://ftp.csiro.au/wil00p/) wii_1km.zip

The data is in geographics wgs84, projected from the lamberts (90m) to
geographics (0.01 degrees) using bilinear resampling. Lakes and water bodies
appear as nodata. The  version ending in 'e' has values assigned to nodata
areas based on a Euclidean allocation (nearest) and masked by the domain we
have been using Nationally as a seamless coverage for modelling.

regards,
Kristen
 1kmGDMsubstrateparent_NationalGeophysicsData_WII.xml 40.3 KB   Download Dec 3, 2012 Project Member `#1` leebel...@gmail.com 
This would be good to get loaded, but as High priority
 Labels: -Priority-Critical Priority-High Jul 8, 2013 Project Member `#2` leebel...@gmail.com 
Reason for update? I presume new/improved data. Changing to 'Medium' for now given other priorities.
 Labels: -Priority-High Priority-Medium

**Comment by adam-collins** [comment]
name: weathering_intensity_v2
id: 2018

**Comment by adam-collins** [comment]
Is this OK for prod?

**Comment by Tasilee** [comment]
Yes, ok for prod. Delete el967.

**Comment by adam-collins** [comment]
On prod.

**Comment by adam-collins** [comment]
Disabled el967
