### ISSUE TITLE
Generate coloured contextual layer legends, and add this to layer-ingestion.

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/layers-service#53]
Coloured styles are now the default for contextual layers on spatial-dev. 

Thumbnails for the layers updated are at http://spatial-dev.ala.org.au/files/newStyles.zip

For layer rendering performance reasons, when the number of classes exceeds 500 an uncoloured legend is used. This includes; aus2,  diwa_type_criteria,  geofabric_Estuary,  geofabric_hydrogeologic,  geofabric_waterbody,  ger_upper_hunter_focus_area_v2,  ilua,  lga_aust,  lith_geologicalunitpolygons1m,  sla_aust,  teow

**Comment by Tasilee** [comment]
These are a vast improvement and they look great. Nice work. 

Re 500+ classes - fully agree. The option to map a class from the legend is then very nice indeed.

Among all those listed, there is a group of layers that have once class - effectively in (inside the polygon/s) and out. As far as the legends go, this is fine, but the one-class layers are not tabulation candidates (separate issue I know - along with another contextual constraint - spatial coverage).
