### ISSUE TITLE
Load Layer MDBA Wetland GIS

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#54]
https://data.gov.au/dataset/wetlands-gis-of-the-murray-darling-basin-series-2-0

required for the MDBA hub

**Comment by ansell** [comment]
To enable both the GROUP and NAME layers to be loaded at the same time they need to be split into separate SHP files, which has been done and loading will be attempted again today.

**Comment by ansell** [comment]
The NAME layer is on the spatial-test server at:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10829

Going to work on the GROUP/GROUPNAME layer again now

**Comment by ansell** [comment]
The GROUP layer is on the spatial-test server again (after filtering out the features that had an empty GROUP attribute):

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10831

Now going to work on adding fields to these layers

**Comment by ansell** [comment]
Fields created successfully at:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10831

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10829
