### ISSUE TITLE
Load Layer: National Vegetation Information System (NVIS) V4.1 Major Groups (33)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#56]
NVIS data is a current gap in our contextual layer data and is of significant value in evaluating/analyzing ALA data. This is a contextual layer, tabulation, facet, gazetteer.

Metadata and download at http://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B21a53368-c383-4ec1-bf51-878b369ce303%7D

Further details http://www.environment.gov.au/land/native-vegetation/national-vegetation-information-system/data-products#mvg41

**Comment by adam-collins** [comment]
ready for metadata
layer: 2125, nvis41_mvg

**Comment by Tasilee** [comment]
Done on Dev

**Comment by adam-collins** [comment]
on prod
