### ISSUE TITLE
Load Layer: National Vegetation Information System (NVIS) V4.1 Subgroups (85)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#57]
Same justification and parameters as per #56 

Metadata and download at http://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B21a53368-c383-4ec1-bf51-878b369ce303%7D

**Comment by adam-collins** [comment]
ready for metadata
layer: 2124, nvis41_mvs

**Comment by Tasilee** [comment]
Done on Dev

**Comment by adam-collins** [comment]
on prod
