### ISSUE TITLE
Load Layer - Conservation Management zones

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#58]
http://www.environment.gov.au/biodiversity/conservation-management-zones

need to find a downloadable version

**Comment by rp-ala** [comment]
Likely accessible from Dept of Environment, ERIN.

**Comment by Tasilee** [comment]
http://www.environment.gov.au/fed/catalog/search/resource/downloadData.page?uuid=%7B98EA7E0D-8E99-4C33-93FB-C5E1E10418E6%7D

**Comment by ansell** [comment]
In queue to be loaded to spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10896

**Comment by ansell** [comment]
Hi @adam-collins, can you review this during the spatial sprint, but not merge it across until Cassandra/Solr/Biocache/BIE upgrades are completed.
