### ISSUE TITLE
Investigate alternatives for access to spatial environmental data

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#59]
http://www.environment.gov.au/about-us/environmental-information-data/web-services

has a number of layers available WFS can we load layers from this- automation would be good

**Comment by Tasilee** [comment]
In theory, I agree as one would expect these to be current. FYI, we did try using WFS internally many years back and gave up as it could not handle the speed required.

If you want to do any analysis in the SP, then we need to do a fair amount of processing - and the type depends on layer type (environmental, contextual).

The other aspect is licencing. With CC type, we can usually make raw data available (as per WFS) but if not, we have used WMS as it is an image of the data, not the data itself.

The Add to Map | Layers allows users to add any known and available WMS layer/s

**Comment by djtfmartin** [comment]
I don't see how we can support sampling without access to the raw SHP or grid files.
So these services might be useful for a quick presentation of a layer, but there aren't useful for any analysis.

Any thoughts @adam-collins ?

**Comment by raymondben** [comment]
Back in the day, there was the WCS protocol for delivering gridded data 
(as actual data, not an image). I haven't kept abreast of OGC stuff, so 
I don't know if WCS is still an option. The DoE site doesn't appear to 
provide it at the moment, but maybe it's something they can switch on at 
the MapServer software end?

**Comment by djtfmartin** [comment]
Thanks @raymondben. We've discussed WCS but we don't have anything working against WCS currently. Something to investigate further.

**Comment by M-Nicholls** [comment]
can we build a temporary shp or gridded file from a wfs and use it for the sampling?

**Comment by adam-collins** [comment]
You can download a shp from WFS. Given our metadata fields, there is probably not much that can be automated.

WFS supports feature extraction. We can get shapefiles with: ogr2ogr -f "ESRI Shapefile" Commonwealth_Heritage_List.shp WFS:http://www.environment.gov.au/mapping/services/ogc_services/Commonwealth_Heritage_List/MapServer/WFSServer

I did not try them all
- World Heritage Areas and Commonwealth_Heritage_List worked
- capad reported a server error

**Comment by Tasilee** [comment]
I had not noticed the comments on this issue. DoEE is one of 50+ sources, each with their own delivery format. Yes, WMS is probably the low hanging fruit, and I'd agree with Ben that WCS would be nice for most of what we have. 

We need to merge this issue and https://github.com/AtlasOfLivingAustralia/spatial-service/issues/29 into an issue that triggers a serious discussion on how we scale over the next 5 years.  [There is also a 'review layers item on the agenda but not a GitHub issue].
