### ISSUE TITLE
Load Layer - update Indigenous Protected Areas with 2016 version

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#61]
find updated IPA layer and load

**Comment by ansell** [comment]
One source for these seem to be embedded in the larger CAPAD database:

https://www.environment.gov.au/land/nrs/science/capad/2014

**Comment by ansell** [comment]
A direct source is:

https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid={B5B41F5B-25E2-4467-90E0-994C7A009889}

**Comment by ansell** [comment]
License for this is CC-BY

**Comment by ansell** [comment]
Uploaded to spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10837

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10837

**Comment by ansell** [comment]
Changed from using ID and NAME to just NAME, as the spatial-service doesn't actually relabel "ID" with "NAME" as it appears to say it will. In this case ID and NAME are equivalent, with 18/18 unique values for both.

**Comment by ansell** [comment]
Uploaded as "Indigenous Protected Areas 2016" to distinguish from the previous version, "Indigenous Protected Areas 2013" and allow comparisons between the two, as there are significant additions in the 2016 version that may be interesting to some users.

**Comment by ansell** [comment]
Hi @adam-collins , could you review these Indigenous Protected Areas 2016 fields during the spatial sprint but not push them across to production until the Cassandra 3 + Solr 5/6 changes have been completed to ensure we don't push record sizes past their current limit.

**Comment by ansell** [comment]
Hi @adam-collins, as part of the current IEK sprint, I need update the values for this layer in the Biocache, but I need to do it without a net addition of fields to Biocache records. To enable this I have switched off the flag for to 2013 version of this layer, cl2015, by running a Postgres query to set "indb=false" and switched that flag on for the 2016 version of this layer, cl10837. 

Both cl2015 and cl10837 should now be able to be pushed to spatial.ala.org.au. Then another full resample round will be scheduled by the data management team for the Biocache to pick up the 2016 layer values (cl10837). I have searched for references to cl2015 in biocache-store but have not found any there that may need to be handled specially for the resample.

There are 4 references to cl2015 in ala-install config files which I will switch over once the resample occurs:

* Biocollect
* Regions
* Regions (MDBA)
* Oznome Demo (Had not heard of this before, but simple enough to switch it over)

https://github.com/AtlasOfLivingAustralia/ala-install/search?q=cl2015

**Comment by ansell** [comment]
Hi @adam-collins see above for details for this one. cl2015 has had its "include in biocache index" setting switch to false on spatial-test, and cl10837 has had its "include in biocache index" switched to true. The switch was done for this layer because it is a one-to-one replacement in terms of fields and hence will not affect the biocache index record sizes. This is urgently required by @StephanievG for a conference next week. Refs https://github.com/AtlasOfLivingAustralia/seasonal-calendar/issues/39

**Comment by Tasilee** [comment]
The latest is now 2018: https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7BC64658F0-95AD-4209-8D1E-F94BD0A4E827%7D and we have had another prompt from user for this update. I would not remove the 2013 version we have. I am upping the priority here and in Google table.

**Comment by Tasilee** [comment]
I have wondered about the need for an IPA layer if the latest CAPAD (2018: #113) includes IPAs: https://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B4448CACD-9DA8-43D1-A48F-48149FD5FCFD%7D
