### ISSUE TITLE
Load Layer - electorate boundaries

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#64]
current layer is out of date, AEC is reviewing new one:  http://www.aec.gov.au/Electorates/gis/gis_datadownload.htm#national

**Comment by ansell** [comment]
I am loading the updated version that PSMA published in May as part of issue #81

**Comment by ansell** [comment]
These are now in production as cl10872 and cl10874, based on the CC-BY license that PSMA provide for their source, rather than the custom license that AEC provide.
