### ISSUE TITLE
No download and no thumbnails on http://spatial.ala.org.au/layers#

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#67]
Looks like neither of the downloads is working on http://spatial.ala.org.au/layers# and the list doesn't include the thumbnail.

**Comment by adam-collins** [comment]
on dev.

**Comment by Tasilee** [comment]
Nice work. Sorting? Probably best to sort by classifications if no sort ability on columns?

toProd

**Comment by Tasilee** [comment]
This needs urgent attention. Still not working. Also suggest smaller text font by default.
