### ISSUE TITLE
Load Layer - RATSIB Areas (Representative Aboriginal and Torres Straight Islander Body)

### ISSUE THREAD

**Issue by rp-ala** [AtlasOfLivingAustralia/layers-service#71]
Spatial boundaries of RATSIB (Representative Aboriginal and Torres Straight Islander Body) areas

www.nntt.gov.au/

**Comment by ansell** [comment]
PDF version of a map for this ar:

http://www.nntt.gov.au/Maps/RATSIB_map.pdf

**Comment by ansell** [comment]
Spatial data reference at:

http://www.nntt.gov.au/assistance/Geospatial/Pages/Spatial-aata.aspx

With downloads (including other shapefiles together with the RATSIB Areas) at:

http://www.ntv.nntt.gov.au/intramaps/download/download.asp

**Comment by ansell** [comment]
Uploaded to spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10836

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10836

**Comment by ansell** [comment]
Changed from using ID and NAME to just NAME, as the spatial-service doesn't actually relabel "ID" with "NAME" as it appears to say it will. In this case ID and NAME are equivalent, with 18/18 unique values for both.

**Comment by ansell** [comment]
Added a new field for the organisations (ORG field in shapefile) as they appear on the PDF version of the map at:

http://www.nntt.gov.au/Maps/RATSIB_map.pdf

The organisation field is:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10838

**Comment by StephanievG** [comment]
Hi Peter - I added to the google doc another ABS layer that should include: remoteness (unless we already have it)

**Comment by ansell** [comment]
Thanks @StephanievG, I have added it as issue #79 to track it.

**Comment by ansell** [comment]
Hi @adam-collins , could you review these RATSIB fields during the spatial sprint but not push them across to production until the Cassandra 3 + Solr 5/6 changes have been completed to ensure we don't push record sizes past their current limit.

**Comment by ansell** [comment]
@adam-collins I have switched off the biocache index setting so cl10836 can be pushed across to spatial.ala.org.au without affecting biocache record sizes. This is urgently required by @StephanievG for a conference next week. Refs https://github.com/AtlasOfLivingAustralia/seasonal-calendar/issues/39
