### ISSUE TITLE
Load Layer - Indigenous Land Use Agreements (ILUA) - update

### ISSUE THREAD

**Issue by rp-ala** [AtlasOfLivingAustralia/layers-service#73]
spatial boundaries of Indigenous Land Use Agreements

This is loaded already, but needs to be updated.

www.nntt.gov.au/

**Comment by ansell** [comment]
Spatial data reference at:

http://www.nntt.gov.au/assistance/Geospatial/Pages/Spatial-aata.aspx

With downloads (including other shapefiles together with the RATSIB Areas) at:

http://www.ntv.nntt.gov.au/intramaps/download/download.asp

**Comment by ansell** [comment]
Existing layer at:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/2010

Only currently using the NAME field, which indicates in this case the name of the agreement, not the name of the RNTBC or similar that asked for the agreement. 

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl2010

The name of the applicant is in the APPLICANT field and needs to be added to the ALA for matching between layers.

The NAME field in the previous load only had 181 unique values, where the dataset currently available has 1107 unique values for NAME, and 592 unique values for APPLICANT. Will preserve the previous layer and date the current layer as 2016 to enable comparisons.

The previous download was performed via Geosciences Australia, where the current download is direct from NNTT:

http://www.ga.gov.au/products/servlet/controller?event=FILE_SELECTION&catno=78643

versus...

http://www.ntv.nntt.gov.au/intramaps/download/ILUA_Registered_Notified_Nat_shp.zip

**Comment by ansell** [comment]
Layer loaded into spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10841

Fields for NAME, APPLICANT and AGTYPE created:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10841

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl110841

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl210841

**Comment by ansell** [comment]
Also added:

SUBJMATTER (Subject matter):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl310841

AGSTATUS (Agreement status):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl410841

AGAUTH (Agreement authority):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl510841

**Comment by ansell** [comment]
Hi @adam-collins , could you review these Indigenous Land Use Agreements fields during the spatial sprint but not push them across to production until the Cassandra 3 + Solr 5/6 changes have been completed to ensure we don't push record sizes past their current limit.

**Comment by ansell** [comment]
@adam-collins cl2010 has not been changed. Could you push the 10841 layer across to spatial.ala.org.au for @StephanievG this week if possible? Refs https://github.com/AtlasOfLivingAustralia/seasonal-calendar/issues/39
