### ISSUE TITLE
LOAD LAYER: topo position

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-service#8]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=90
_date:_ Thu Aug  8 16:20:33 2013
_author:_ moyesyside

---

Original Issue reported by Project Member Reported by chris.fl...@gmail.com, May 27, 2012 - [https://code.google.com/p/alageospatialportal/issues/detail?id=991](https://code.google.com/p/alageospatialportal/issues/detail?id=991)

Project Member Reported by chris.fl...@gmail.com, May 27, 2012 
From Kristen Williams:

Hi Lee,

Here’s the LF7RUP datasets. It is a categorical dataset. I’ve included this as a float grid which is the format required by GDM.  However, GDM doesn’t work with categorical data – only continuous and ordinal…I don’t use this in GDM modelling, but it may be effective in Maxent modelling. This is the 0.01 grid version. I’m still working on the 250m grid data. 

As in all the data I provide, the coastline of the 1km grid has been expanded a few cells to ensure full coverage and nodata cells have been filled to ensure consistency in data/nodata and modelling extent (a requirement for GDM analysis). 

The custodian is ANU, but Brenda Mackey was the contact – Brendan is now based with Griffith at the Gold Coast. 

I haven’t yet generated metadata also for this version of the layer, and will put that task on my to-do list. 

Cheers,

Kristen

 lf7rupw_1ke.zip 3.3 MB   Download Jun 6, 2013 Project Member `#1` chris.fl...@gmail.com 
(No comment was entered for this change.)
 Cc: moyesyside Jun 6, 2013 Project Member `#2` chris.fl...@gmail.com 
Hi Lee,

Are we still interested in this layer and is it priority critical?

Cheers,
Chris
 Jun 6, 2013 Project Member `#3` leebel...@gmail.com 
Let's lower the priority until we hear about any requests for it. Topographic position will certainly be more relevant at the 250m grid that 1km (0.01 degree) - particularly for vegetation where this data can highly influence the species composition.
 Jun 6, 2013 Project Member `#4` chris.fl...@gmail.com 
(No comment was entered for this change.)
 Labels: -Priority-Critical Priority-Medium Jun 6, 2013 Project Member `#5` chris.fl...@gmail.com 
(No comment was entered for this change.)
 Labels: -Priority-Medium Priority-Low Jul 11, 2013 Project Member `#6` leebel...@gmail.com 
Kristen: I assume the categories are something like 'ridge', 'upper slope','mid-slope', 'lower slope' and 'valley'? Certainly could be useful in Sampling, MaxEnt and tabulation.

This dataset would only be of use at the 250m resolution (and with metadata :))  
 Cc: Kristen....@csiro.au

**Comment by adam-collins** [comment]
name: Topographical Position
id: 2051

Needs metadata.

Hover value and use in analysis will return the numerical value. Legend image has both the label and the numerical value.

Is it useful to use this layer as an environmental? Does it need to be flagged as a contextual when run in maxent? I can try to change it to a contextual if that is more appropriate.

**Comment by Tasilee** [comment]
This is a tricky one is that it could be treated as a contextual or environmental layer. Environmental only in that class values 1-7 show some topographic position order - ridge to flats. But you can't say 7 = 7 x 1 or even that 7 > 6 > 5 > 4 > 3 > 2 > 1 so my feeling is that it should be contextual.

**Comment by Tasilee** [comment]
I cannot find any online metadata information for this layer so have emailed a friend at the Fenner School. A link to an external online resource would be ideal but this isn't always going to be available. 

An alternative, as in this case is that I have a zip file with metadata. Can we file such metadata on our system?

**Comment by adam-collins** [comment]
If it is not appropriate for 'notes' we can put it up into /files.

**Comment by Tasilee** [comment]
Far more than appropriate for 'notes' See https://www.dropbox.com/s/jpnxed2bhp71269/Topo_position_lf7rupw_1ke.zip?dl=0

**Comment by adam-collins** [comment]
Can put the pdf into /files for a URL such as http://spatial.ala.org.au/files/Read_me_topo_position.pdf or under a subdirectory, or the whole zip.

**Comment by Tasilee** [comment]
My feeling is a subdirectory  - /files/metadata and just the pdf as we have no authority to redistribute

**Comment by adam-collins** [comment]
URL for layers metadata entry http://spatial.ala.org.au/files/metadata/topo_position.pdf

**Comment by Tasilee** [comment]
Nice, but I can't see a link from the (i) entry
![capture](https://cloud.githubusercontent.com/assets/6656350/6340333/71c71de0-bc12-11e4-98f6-d328bdc2207c.jpg)

**Comment by adam-collins** [comment]
Edited the layer record. It is there now.

**Comment by Tasilee** [comment]
Yep. Thanks.

**Comment by Tasilee** [comment]
OK. This layer only makes sense at 250m resolution. It is a 'Priority-low'

**Comment by Tasilee** [comment]
The Soil and landscape grid data supersedes this (#32)
