### ISSUE TITLE
Import layer set should handle one UID per line

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#84]
The ability to import the (full) layer UIDs for layer selection is very handy but the format expected is too narrow. Suggest the ability to have one UID/line with or without "," would be more general.

**Comment by ansell** [comment]
This looks like a spatial-hub issue rather than `layers-service` which we have been using for tracking layer loads

**Comment by peggynewman** [comment]
included in new spatial hub
