### ISSUE TITLE
Load Layer - Species of National Environmental Significance Database 10km Grids

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/layers-service#87]
Species of National Environmental Significance Database 10km Grids available from the Department of Environment:

http://www.environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B337B05B6-254E-47AD-A701-C55D9A0435EA%7D

This is in addition to the Ecological Communities of National Significance that has been loaded into spatial-test already. See issue #60

**Comment by peggynewman** [comment]
Update for Aug 2019 grids (EDs)
