### ISSUE TITLE
Load layer: World Marine Boundaries

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#89]
This looks like a 'must add':

MarineRegions.org is proud to launch the new version of the Maritime Boundaries Geodatabase. In this new release, Marine Regions updates the global Exclusive Economic Zones (EEZ) (version 9), and launches global datasets for Territorial Seas (TS), Contiguous Zones (CZ), Internal Waters (IW) and Archipelagic Waters (AW). The global baseline used in this new version is a combination of the publically available straight and archipelagic baselines and the coastline as a proxy for the low-water line. The source for the straight baselines is the United Nations repository on maritime claims, together with national publications on maritime delimitations and agreements. The ESRI Countries 2014 database has been used as the primary source for the Maritime Boundaries coastline. The coastline was further updated with reefs data extracted from the Coral Reef Distribution database from UNEP for the countries where reefs were fundamental for the correct calculation of the maritime areas. 

With the new release, we hope to further serve the global marine data user community working on geospatial analysis. As Marine Regions depends on data and knowledge sharing from global, European, regional and national data providers and relevant experts, we aim to set up Collaboration Agreements with our users and data providers. An example template of a Collaboration Agreement can be found online, please contact info@marineregions.org if your organization is interested to explore this collaboration.

All datasets from marineregions.org’s Maritime Boundaries Geodatabase continue to be the only freely-available global datasets on the World’s Maritime Boundaries.

**Comment by ansell** [comment]
There are a large number of downloads (26 or so) from marineregions.org. Are we targeting this at a subset of those or the complete set?

**Comment by Tasilee** [comment]
- World EEZ v10 (2018-02-21, 119 MB)
- World 24 Nautical Miles Zone (Contiguous Zone) v2 (2018-02-21, 44 MB)
- World 12 Nautical Miles Zone (Territorial Seas) v2 (2018-02-21, 50 MB)

**Comment by peggynewman** [comment]
Superseded by https://github.com/AtlasOfLivingAustralia/layers-service/issues/126
