### ISSUE TITLE
Load Layer: Add 250m gridded terrestrial environmental data (Kristen Williams)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/layers-service#9]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=92
_date:_ Thu Aug  8 16:20:58 2013
_author:_ moyesyside

---

Original Issue reported by Project Member Reported by leebel...@gmail.com, Mar 21, 2011 - [https://code.google.com/p/alageospatialportal/issues/detail?id=442](https://code.google.com/p/alageospatialportal/issues/detail?id=442)

Project Member Reported by leebel...@gmail.com, Mar 21, 2011 
The 1km data is fine for all but the hilly parts of Oz. Given the inevitable GER and associated regional projects, we need to move to the tried and true 250m grid.

Kristen will need to provide these layers in collaboration with others such as Jane Elith, Mike Hutchinson and Janet Stein.

The 250m grid would need to align with the 1km grid. It would not replace it.

Post UI re-design and pre GER grumbles.
 May 24, 2011 Project Member `#1` leebel...@gmail.com 
To High

Initial Dynamic Vegetation Cover as trial. Main issue: Need to consider how we handle the 250m layers (of which we will eventually have around 50 frgom Kristen).

Can we use WMS or WCS to support dynamic generation of a selected polygon (area option)

Store Classes as separate WMS or WCS for Gaz?
 Labels: -Priority-Medium Priority-High May 24, 2011 Project Member `#2` leebel...@gmail.com 
Started
 Status: Started Jun 30, 2011 `#3` gavin.ja...@gmail.com 
(No comment was entered for this change.)
 Owner: gavin.ja...@gmail.com Jun 30, 2011 Project Member `#4` leebel...@gmail.com 
(No comment was entered for this change.)
 Cc: -gavin.ja...@gmail.com leebel...@gmail.com Jul 10, 2011 Project Member `#5` leebel...@gmail.com 
Set medium until Kristen delivers. Emailing her today.
 Labels: -Priority-High Priority-Medium Aug 10, 2011 Project Member `#6` leebel...@gmail.com 
I'm inclined to finish off dynamic vegetation cover and raise a new issue once we get the 250m climate layers from Kristen. Upping this now to critical to enable remaining points to be addressed and issue closed (we need to get this layer public asap).

Remaining: 
1. Support for hover tool
2. I know that there are multiple time periods. Did we get any? If so, we need to decide what to use. I'd like to see at least 3 different time slices.
   Nov 22, 2011 `#7` gavin.ja...@gmail.com 
   Reassigning to Chris - this will become a higher priority once the 250m res layers are received.

Note that the dynamic landcover layer (918, dlcmv1) still requires updated metadata on dev before being released to prod, discuss this with Lee upon your return - he has a contact named Leo who may be able to assist.
 Owner: chris.fl...@gmail.com Apr 25, 2012 Project Member `#8` leebel...@gmail.com 
Lowering. On demand layers.
 Labels: -Priority-Medium Priority-Low Apr 25, 2012 Project Member `#9` leebel...@gmail.com 
(No comment was entered for this change.)
 Labels: -Priority-Low Priority-Critical May 13, 2012 Project Member `#10` chris.fl...@gmail.com 
Lee - this was set to low and the back up to critical - which is it? If it's critical can you give me some further details about it? Thanks.
 May 13, 2012 Project Member `#11` leebel...@gmail.com 
We are dependent on Kristen supplying these layers and given her workload on the NPEI and other work, I'm not sure it will happen by June 30. Set to Low and triggered review on receipt of layers. Kristen addd to issue. Adam removed.
 Cc: -adam_col...@tpg.com.au Kristen....@csiro.au Labels: -Priority-Critical Priority-Low Jul 11, 2013 Project Member `#12` leebel...@gmail.com 
This is an ideal issue for the 'environmental layer committee'. Do we replace the 1km layers? My feeling would be yes.
 Cc: moyesyside

**Comment by adam-collins** [comment]
Do we have this data?

**Comment by Tasilee** [comment]
No, but Kristen can deliver when we are ready. These were a lower priority.

Lee

From the Pad

**Comment by Tasilee** [comment]
Email from Kristen Williams December 11, 2018 regards updated 9 second grid climatic layers: https://doi.org/10.4225/08/5afa9f7d1a552

**Comment by Tasilee** [comment]
Superseded by #82
