### ISSUE TITLE
load layer - Forrests Australia

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/layers-service#90]
load the three v2.0 layers here: http://www.agriculture.gov.au/abares/forestsaustralia/forest-data-maps-and-tools/forest-data

Forests of Australia (2013) v2.0
Tenure of Australia's forests (2013) v2.0
Australia's Indigenous forest estate (2013) v2.0

**Comment by ansell** [comment]
Loaded into spatial-test as:

Australia's Indigenous forest estate (2013) v2.0:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10900

Forests of Australia (2013) v2.0:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10902

Tenure of Australia's forests (2013) v2.0:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10903

**Comment by ansell** [comment]
@adam-collins I have now set these three fields to be added to the biocache index. Let me know when they have been sent across to production spatial and I will start a full resample/process cycle.

**Comment by adam-collins** [comment]
These layers are now on production.

**Comment by ansell** [comment]
Thanks, I will start the process/resamples going
