### ISSUE TITLE
User request to change layer categories from Substrate to Soil

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/layers-service#93]
A user has requested that we change the layer categories that currently refer to Substrate to Soil to reflect their biodiversity:

> While I am at it may I suggest you change most of the substrate references to soil references.  
> Soils are not inert substrates but contain most terrestrial biodiversity.  
> They should be respected more

I am not familiar with how the categories are created/curated, but this may just require an SQL query.

**Comment by Tasilee** [comment]
I created the layers classification (and would prefer to maintain/extend it). 

I used "substrate" very specifically as a broader category than "soil" and I think "regolith" would be less well known. In short, I'm not convinced that "soil" is better.
