### ISSUE TITLE
Load Layer: MERRAclim - A new world coverage climate dataset

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/layers-service#95]
See http://datadryad.org/resource/doi:10.5061/dryad.s2v81. I'd like for us to get the following sets-

MERRAclim. 2_5m_max_00s
MERRAclim. 2_5m_max_90s
MERRAclim. 2_5m_max_80s
MERRAclim. 2_5m_mean_00s
MERRAclim. 2_5m_mean_90s
MERRAclim. 2_5m_mean_80s
MERRAclim. 2_5m_min_00s
MERRAclim. 2_5m_min_90s
MERRAclim. 2_5m_min_80s

Reference: http://www.nature.com/articles/sdata201778

**Comment by Tasilee** [comment]
Update: To rationalize layers, load only 

MERRAclim. 2_5m_mean_00s

**Comment by ansell** [comment]
The layers that Adam has loaded so far are the `2.5m_mean_00s` grids for each of the following:

1. MerraClim: Annual Mean Temperature (bio01) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10958
1. MerraClim: Mean Diurnal Range (bio2) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10976
1. MerraClim: Isothermality (bio3) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10975
1. MerraClim: Temperature Seasonality (bio4) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10974
1. MerraClim: Max Temperature of Warmest Month (bio5) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10973
1. MerraClim: Min Temperature of Coldest Month (bio6) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10972
1. MerraClim: Temperature Annual Range (bio7) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10971
1. MerraClim: Mean Temperature of Wettest Quarter (bio8) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10970
1. MerraClim: Mean Temperature of Driest Quarter (bio9) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10969
1. MerraClim: Mean Temperature of Warmest Quarter (bio10) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10968
1. MerraClim: Mean Temperature of Coldest Quarter (bio11) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10967
1. MerraClim: Annual Precipitation (bio12) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10966
1. MerraClim: Precipitation of Wettest Month (bio13) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10965
1. MerraClim: Precipitation of Driest Month (bio14) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10964
1. MerraClim: Precipitation Seasonality (bio15) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10963
1. MerraClim: Precipitation of Wettest Quarter (bio16) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10962
1. MerraClim: Precipitation of Driest Quarter (bio17) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10961
1. MerraClim: Precipitation of Warmest Quarter (bio18) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10960
1. MerraClim: Precipitation of Coldest Quarter (bio19) https://nectar-spatial-staging.ala.org.au/ws/manageLayers/layer/10959

**Comment by ansell** [comment]
`bio01` shows up okay in the the spatial-hub instance on `nectar-spatial-staging`, but the others are not completely loaded into some component currently, failing with similar error messages to the following:

```
==> /var/log/tomcat7/catalina.out <==
org.geowebcache.GeoWebCacheException: Thread 3275 Unknown layer ALA:merraclim_bio18. Check the logfiles, it may not have loaded properly.
```

Putting this issue into "Waiting" on the board until those issues are resolved.

**Comment by peggynewman** [comment]
No longer using Merraclim layers ... @adam-collins all 19 layers should be removed from nectar-staging now, is that right?
